### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "method": "findById",
  "args": [100]
}

### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.OrderService",
  "method": "findById",
  "args": [200]
}

### mock
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "method": "hashCode",
  "args": []
}