### 获取用户信息8088 consumer
POST http://localhost:8088/?id=55

### 通过8088调用接口 测试超时接口
POST http://localhost:8088/find?timeout=3500

### 修改灰度比例值
GET http://localhost:8088/gray?ratio=100

### 通过8081调用接口 修改超时
GET http://localhost:8081/ports?ports=8080,8094

### 获取用户信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "methodSign": "bd8865f6f7cf984189f489fa16c34db3",
  "args": [100]
}

### 获取用户信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "methodSign": "fd6be21ff9e15424ea10347ea5f095af",
  "args": [100, "yj"]
}

### 获取订单信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.OrderService",
  "methodSign": "e807ca579df5e6b2e0b8b999457e2439",
  "args": [200]
}

### mock
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.abysscat.catrpc.demo.api.UserService",
  "methodSign": "hashCode",
  "args": []
}