server:
  port: 8081

catrpc:
  zkServer: localhost:2181
  zkRoot: catrpc

app:
  id: app1
  namespace: public
  env: dev
  version: v1

logging:
  level:
    root: info
    com.abysscat.catrpc: debug