app:
  id: catrpc

server:
  port: 8081

catrpc:
  zk:
    server: localhost:2181
    root: catrpc
  app:
    id: app1
    namespace: public
    env: dev
    version: v1
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 20

catregistry:
  servers: http://localhost:8484

logging:
  level:
    root: info
    com.abysscat.catrpc: debug

apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: app1
    eagerLoad:
      enabled: false