server:
  port: 8088

catrpc:
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zkServer: localhost:2181
  zkRoot: catrpc

app:
  id: app1
  namespace: public
  env: dev
  version: v1
  retries: 2
  timeout: 600
  grayRatio: 10 # todo 可放到apollo配置中心，实时热更新

logging:
  level:
    root: info
    com.abysscat.catrpc: debug